local wezterm = require("wezterm")
return {
	color_scheme = "Catppuccin Latte",
	-- color_scheme = "rose-pine-moon",
	enable_tab_bar = false,
	font_size = 16.0,
	font = wezterm.font("ComicCodeLigatures Nerd Font"),
	-- font = wezterm.font("MonoLisa Nerd Font"),
	macos_window_background_blur = 90,
	window_decorations = "RESIZE",
	keys = {
		{ key = "a", mods = "ALT", action = wezterm.action({ SendString = "\x1ba" }) },
		{ key = "b", mods = "ALT", action = wezterm.action({ SendString = "\x1bb" }) },
		{ key = "c", mods = "ALT", action = wezterm.action({ SendString = "\x1bc" }) },
		{ key = "d", mods = "ALT", action = wezterm.action({ SendString = "\x1bd" }) },
		{ key = "e", mods = "ALT", action = wezterm.action({ SendString = "\x1be" }) },
		{ key = "f", mods = "ALT", action = wezterm.action({ SendString = "\x1bf" }) },
		{ key = "g", mods = "ALT", action = wezterm.action({ SendString = "\x1bg" }) },
		{ key = "h", mods = "ALT", action = wezterm.action({ SendString = "\x1bh" }) },
		{ key = "i", mods = "ALT", action = wezterm.action({ SendString = "\x1bi" }) },
		{ key = "j", mods = "ALT", action = wezterm.action({ SendString = "\x1bj" }) },
		{ key = "k", mods = "ALT", action = wezterm.action({ SendString = "\x1bk" }) },
		{ key = "l", mods = "ALT", action = wezterm.action({ SendString = "\x1bl" }) },
		{ key = "m", mods = "ALT", action = wezterm.action({ SendString = "\x1bm" }) },
		{ key = "n", mods = "ALT", action = wezterm.action({ SendString = "\x1bn" }) },
		{ key = "o", mods = "ALT", action = wezterm.action({ SendString = "\x1bo" }) },
		{ key = "p", mods = "ALT", action = wezterm.action({ SendString = "\x1bp" }) },
		{ key = "q", mods = "ALT", action = wezterm.action({ SendString = "\x1bq" }) },
		{ key = "r", mods = "ALT", action = wezterm.action({ SendString = "\x1br" }) },
		{ key = "s", mods = "ALT", action = wezterm.action({ SendString = "\x1bs" }) },
		{ key = "t", mods = "ALT", action = wezterm.action({ SendString = "\x1bt" }) },
		{ key = "u", mods = "ALT", action = wezterm.action({ SendString = "\x1bu" }) },
		{ key = "v", mods = "ALT", action = wezterm.action({ SendString = "\x1bv" }) },
		{ key = "w", mods = "ALT", action = wezterm.action({ SendString = "\x1bw" }) },
		{ key = "x", mods = "ALT", action = wezterm.action({ SendString = "\x1bx" }) },
		{ key = "y", mods = "ALT", action = wezterm.action({ SendString = "\x1by" }) },
		{ key = "z", mods = "ALT", action = wezterm.action({ SendString = "\x1bz" }) },
		{ key = "1", mods = "ALT", action = wezterm.action({ SendString = "\x1b1" }) },
		{ key = "2", mods = "ALT", action = wezterm.action({ SendString = "\x1b2" }) },
		{ key = "3", mods = "ALT", action = wezterm.action({ SendString = "\x1b3" }) },
		{ key = "4", mods = "ALT", action = wezterm.action({ SendString = "\x1b4" }) },
		{ key = "5", mods = "ALT", action = wezterm.action({ SendString = "\x1b5" }) },
		{ key = "6", mods = "ALT", action = wezterm.action({ SendString = "\x1b6" }) },
		{ key = "7", mods = "ALT", action = wezterm.action({ SendString = "\x1b7" }) },
		{ key = "8", mods = "ALT", action = wezterm.action({ SendString = "\x1b8" }) },
		{ key = "9", mods = "ALT", action = wezterm.action({ SendString = "\x1b9" }) },
		{ key = "0", mods = "ALT", action = wezterm.action({ SendString = "\x1b0" }) },
		{ key = "`", mods = "ALT", action = wezterm.action({ SendString = "\x1b`" }) },
		{ key = "-", mods = "ALT", action = wezterm.action({ SendString = "\x1b-" }) },
		{ key = "=", mods = "ALT", action = wezterm.action({ SendString = "\x1b=" }) },
		{ key = "[", mods = "ALT", action = wezterm.action({ SendString = "\x1b[" }) },
		{ key = "]", mods = "ALT", action = wezterm.action({ SendString = "\x1b]" }) },
		{ key = "\\", mods = "ALT", action = wezterm.action({ SendString = "\x1b\\" }) },
		{ key = ";", mods = "ALT", action = wezterm.action({ SendString = "\x1b;" }) },
		{ key = "'", mods = "ALT", action = wezterm.action({ SendString = "\x1b'" }) },
		{ key = ",", mods = "ALT", action = wezterm.action({ SendString = "\x1b," }) },
		{ key = ".", mods = "ALT", action = wezterm.action({ SendString = "\x1b." }) },
		{ key = "/", mods = "ALT", action = wezterm.action({ SendString = "\x1b/" }) },
		{ key = " ", mods = "ALT", action = wezterm.action({ SendString = "\x1b " }) },
		{ key = "Enter", mods = "ALT", action = wezterm.action({ SendString = "\x1b\r" }) },
		-- { key = "Up", mods = "ALT", action = wezterm.action({ SendString = "\x1b[A" }) },
		-- { key = "Down", mods = "ALT", action = wezterm.action({ SendString = "\x1b[B" }) },
		-- { key = "Left", mods = "ALT", action = wezterm.action({ SendString = "\x1b[D" }) },
		-- { key = "Right", mods = "ALT", action = wezterm.action({ SendString = "\x1b[C" }) },
		{ key = "a", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🚀" }) },
		{ key = "b", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🌟" }) },
		{ key = "c", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🎉" }) },
		{ key = "d", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🎈" }) },
		{ key = "e", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🎁" }) },
		{ key = "f", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🎄" }) },
		{ key = "g", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🎃" }) },
		{ key = "h", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🎆" }) },
		{ key = "i", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🎇" }) },
		{ key = "j", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🎸" }) },
		{ key = "k", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🎤" }) },
		{ key = "l", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🎵" }) },
		{ key = "m", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🎶" }) },
		{ key = "n", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🏆" }) },
		{ key = "o", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🏅" }) },
		{ key = "p", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🥇" }) },
		{ key = "q", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🥈" }) },
		{ key = "r", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🥉" }) },
		{ key = "s", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🚴" }) },
		{ key = "t", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🚵" }) },
		{ key = "u", mods = "CMD|SHIFT", action = wezterm.action({ SendString = "🏋️" }) },

		-- Command+Letter
		{ key = "Tab", mods = "CTRL", action = wezterm.action({ SendString = "🍑" }) },
		{ key = "a", mods = "CMD", action = wezterm.action({ SendString = "😀" }) },
		{ key = "b", mods = "CMD", action = wezterm.action({ SendString = "😁" }) },
		{ key = "c", mods = "CMD", action = wezterm.action({ SendString = "😂" }) },
		{ key = "d", mods = "CMD", action = wezterm.action({ SendString = "🤣" }) },
		{ key = "e", mods = "CMD", action = wezterm.action({ SendString = "😃" }) },
		{ key = "f", mods = "CMD", action = wezterm.action({ SendString = "😄" }) },
		{ key = "g", mods = "CMD", action = wezterm.action({ SendString = "😅" }) },
		{ key = "h", mods = "CMD", action = wezterm.action({ SendString = "😆" }) },
		{ key = "i", mods = "CMD", action = wezterm.action({ SendString = "😉" }) },
		{ key = "j", mods = "CMD", action = wezterm.action({ SendString = "😊" }) },
		{ key = "k", mods = "CMD", action = wezterm.action({ SendString = "😋" }) },
		{ key = "l", mods = "CMD", action = wezterm.action({ SendString = "😎" }) },
		{ key = "m", mods = "CMD", action = wezterm.action({ SendString = "😍" }) },
		{ key = "n", mods = "CMD", action = wezterm.action({ SendString = "😘" }) },
		{ key = "o", mods = "CMD", action = wezterm.action({ SendString = "😗" }) },
		{ key = "p", mods = "CMD", action = wezterm.action({ SendString = "😙" }) },
		-- { key = "q", mods = "CMD", action = wezterm.action({ SendString = "😚" }) },
		{ key = "r", mods = "CMD", action = wezterm.action({ SendString = "🙂" }) },
		{ key = "s", mods = "CMD", action = wezterm.action({ SendString = "🤗" }) },
		{ key = "t", mods = "CMD", action = wezterm.action({ SendString = "🤩" }) },
		{ key = "u", mods = "CMD", action = wezterm.action({ SendString = "🤔" }) },
		-- { key="v", mods="CMD", action=wezterm.action{SendString="🤨"} }, -- Commented out as per the original configuration
		{ key = "w", mods = "CMD", action = wezterm.action({ SendString = "😐" }) },
		{ key = "x", mods = "CMD", action = wezterm.action({ SendString = "😑" }) },
		{ key = "y", mods = "CMD", action = wezterm.action({ SendString = "😶" }) },
		{ key = "z", mods = "CMD", action = wezterm.action({ SendString = "🙄" }) },

		-- Numbers
		{ key = "1", mods = "CMD", action = wezterm.action({ SendString = "🌟" }) },
		{ key = "2", mods = "CMD", action = wezterm.action({ SendString = "🔥" }) },
		{ key = "3", mods = "CMD", action = wezterm.action({ SendString = "🌈" }) },
		{ key = "4", mods = "CMD", action = wezterm.action({ SendString = "🍀" }) },
		{ key = "5", mods = "CMD", action = wezterm.action({ SendString = "🌹" }) },
		{ key = "6", mods = "CMD", action = wezterm.action({ SendString = "🎵" }) },
		{ key = "7", mods = "CMD", action = wezterm.action({ SendString = "⚡" }) },
		{ key = "8", mods = "CMD", action = wezterm.action({ SendString = "🌍" }) },
		{ key = "9", mods = "CMD", action = wezterm.action({ SendString = "🌙" }) },
		{ key = "0", mods = "CMD", action = wezterm.action({ SendString = "⭐" }) },

		-- Non-letter, non-number keys with non-face emojis
		{ key = "Space", mods = "CMD", action = wezterm.action({ SendString = "🔔" }) },
		{ key = "Tab", mods = "CMD", action = wezterm.action({ SendString = "🔑" }) },
		{ key = "Enter", mods = "CMD", action = wezterm.action({ SendString = "📥" }) },
		{ key = "Backspace", mods = "CMD", action = wezterm.action({ SendString = "🗑️" }) },
		-- { key = "-", mods = "CMD", action = wezterm.action({ SendString = "➖" }) },
		{ key = "|", mods = "CMD", action = wezterm.action({ SendString = "➕" }) },
		{ key = "[", mods = "CMD", action = wezterm.action({ SendString = "📚" }) },
		{ key = "]", mods = "CMD", action = wezterm.action({ SendString = "📖" }) },
		{ key = "\\", mods = "CMD", action = wezterm.action({ SendString = "🔙" }) },
		{ key = ";", mods = "CMD", action = wezterm.action({ SendString = "📝" }) },
		{ key = "'", mods = "CMD", action = wezterm.action({ SendString = "✒️" }) },
		{ key = ",", mods = "CMD", action = wezterm.action({ SendString = "🗒️" }) },
		{ key = ".", mods = "CMD", action = wezterm.action({ SendString = "📌" }) },
		{ key = "/", mods = "CMD", action = wezterm.action({ SendString = "🗂️" }) },
		{ key = "`", mods = "CMD", action = wezterm.action({ SendString = "💡" }) },
		-- { key = "Up", mods = "CMD", action = wezterm.action({ SendString = "⬆️" }) },
		-- { key = "Down", mods = "CMD", action = wezterm.action({ SendString = "⬇️" }) },
		-- { key = "Left", mods = "CMD", action = wezterm.action({ SendString = "⬅️" }) },
		-- { key = "Right", mods = "CMD", action = wezterm.action({ SendString = "➡️" }) },
	},
	mouse_bindings = {
		-- Ctrl-click will open the link under the mouse cursor
		-- {
		-- 	event = { Up = { streak = 1, button = "Left" } },
		-- 	mods = "CTRL",
		-- 	action = wezterm.action.OpenLinkAtMouseCursor,
		-- },
	},
}
